version: '3'
services: 
  mydb:
    image: postgres:9.6-alpine
    volumes: 
      - db-data:/var/lib/postgres/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes: 
  db-data:
    driver: local
    